services:
  - type: web
    name: partner-backend
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: PORT
        value: 10000
